### ISSUE TITLE
xDisk - Feature Request - Destructive Switch

### ISSUE THREAD

**Issue by pshellguruwannabe** [PowerShell/StorageDsc#50] opened 2016-08-19 15:34 UTC
Would it be possible to add a Destructive switch to the schema so that existing partitions/volumes could be destroyed with Clear-Disk.  

Thanks.

**Comment by PlagueHO** [comment] 2016-09-28 05:33
@TravisEz13 suggested that the switch should be "AllowDestructive"

**Comment by nyanhp** [comment] 2017-05-17 07:46
Hi @pshellguruwannabe , the issue is quite old but I recently got into resource development and wanted to clarify this parameter. An AllowDestructive switch itself would not mean that the partition schema is always removed when the set method is executed. At the moment it would merely mean that operations that might be destructive like partition resizing would be made possible.

I will likely include another new parameter called ClearDisk to indicate that the entire partition schema of the target disk will be discarded whenever Set-TargetResource is entered (which will likely result in data loss). Is this what you had in mind? This equals Clear-Disk -RemoveData -RemoveOEM whenever Test-TargetResource returns false.

**Comment by TravisEz13** [comment] 2017-05-17 18:56
`AllowDestructive` should not mean always, but that a destructive operation is allowed when `Set-TargetResource` us called.

**Comment by PlagueHO** [comment] 2019-03-08 21:43
I'm going to close this because it has been implemented.

**Closed by PlagueHO** 2019-03-08 21:43 UTC
Labels: enhancement, help wanted
